### ISSUE TITLE
buildversion > 23 rotate 90 degree automatically

### ISSUE THREAD

**Issue by gurkankesgin** [LinXueyuanStdio/timecat#1]
I use your cropper but rotate image automatically 90 degree left after crop the image .

**Comment by LinXueyuanStdio** [comment]
![device-2018-04-03-074331](https://user-images.githubusercontent.com/23211526/38221631-1ee3bc6c-3713-11e8-81a4-9dd5cdb720b3.gif)
but in my device there is no rotation

**Comment by gurkankesgin** [comment]
thanks my fault
