### ISSUE TITLE
我不能在其他其他应用中使用该应用提供的功能

### ISSUE THREAD

**Issue by TututuXi** [LinXueyuanStdio/timecat#2]
我在设置中设置了这些参数，但是为什么不能再其他应用中响应事件
并且，我也无法注册账号，需要翻墙么?
![image](https://user-images.githubusercontent.com/15766876/39563678-bc046aae-4ee3-11e8-8ffd-36707c261905.png)

![image](https://user-images.githubusercontent.com/15766876/39563659-ae6b2446-4ee3-11e8-817c-f04ab37fd32a.png)

**Comment by LinXueyuanStdio** [comment]
1. 双击在有的app里被使用了，微信的话建议使用单击
2. 忽略账号吧，我们服务器没搞上去。现在全部功能都可以用的，没有限制
